cmake_minimum_required(VERSION 3.1.0)

file(TO_NATIVE_PATH "${CMAKE_INSTALL_PREFIX}/include"
  AEYAE_INSTALL_DIR_INCLUDE)

file(TO_NATIVE_PATH "${CMAKE_INSTALL_PREFIX}/lib"
  AEYAE_INSTALL_DIR_LIB)

file(TO_NATIVE_PATH
  "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig"
  INSTALL_LIB_PKGCONFIG_DIR)

find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
  set(ENV{PKG_CONFIG_PATH} "${INSTALL_LIB_PKGCONFIG_DIR}:$ENV{PKG_CONFIG_PATH}")
endif (PKG_CONFIG_FOUND)
