// -*- Mode: c++; tab-width: 8; c-basic-offset: 2; indent-tabs-mode: t -*-
// NOTE: the first line of this file sets up source code indentation rules
// for Emacs; it is also a hint to anyone modifying this file.

/*
Copyright 2004-2007 University of Utah

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/


// NOTE: 
//       DO NOT EDIT THIS FILE, IT IS AUTOGENERATED.
//       ALL CHANGES WILL BE LOST UPON REGENERATION.

#ifndef THE_POINT_SYMBOLS_HXX_
#define THE_POINT_SYMBOLS_HXX_

// local includes:
#include "opengl/the_symbols.hxx"


//----------------------------------------------------------------
// the_point_symbol_id_t
// 
typedef enum
{
  THE_CIRCLE_SYMBOL_E,
  THE_CORNERS_SYMBOL_E,
  THE_CROSS_SYMBOL_E,
  THE_DASH_CROSS_SYMBOL_E,
  THE_DIAG_CROSS_SYMBOL_E,
  THE_DIAG_SQUARE_SYMBOL_E,
  THE_FILLED_CIRCLE_SYMBOL_E,
  THE_FILLED_DIAG_SQUARE_SYMBOL_E,
  THE_FILLED_SQUARE_SYMBOL_E,
  THE_HASH_SYMBOL_E,
  THE_SMALL_CIRCLE_SYMBOL_E,
  THE_SMALL_CORNERS_SYMBOL_E,
  THE_SMALLEST_FILLED_DIAG_SQUARE_SYMBOL_E,
  THE_SMALL_FILLED_CIRCLE_SYMBOL_E,
  THE_SMALL_FILLED_DIAG_SQUARE_SYMBOL_E,
  THE_SMALL_FILLED_SQUARE_SYMBOL_E,
  THE_SMALL_SQUARE_SYMBOL_E,
  THE_SQUARE_SYMBOL_E,
  THE_TRIANGLE_SYMBOL_E,
  THE_TRI_AXIS_SYMBOL_E
} the_point_symbol_id_t;


//----------------------------------------------------------------
// the_point_symbols_t
// 
class the_point_symbols_t : public the_symbols_t
{
public:
  the_point_symbols_t(): the_symbols_t("point") {}
  virtual ~the_point_symbols_t() {}

  // virtual:
  unsigned int width() const  { return 8; }
  unsigned int height() const { return 8; }

  // virtual:
  float x_origin() const { return 4.0; }
  float y_origin() const { return 4.0; }

  // virtual:
  float x_step() const { return 0.0; }
  float y_step() const { return 0.0; }

  // virtual:
  unsigned char * bitmap(const unsigned int & id) const
  { return symbols_[id]; }

  // virtual: the number of display lists to be compiled:
  unsigned int size() const { return 20; }

private:
  static unsigned char symbols_[20][8];
};

//----------------------------------------------------------------
// THE_POINT_SYMBOLS
// 
// a single global instance of the symbols font:
// 
extern the_point_symbols_t THE_POINT_SYMBOLS;


#endif // THE_POINT_SYMBOLS_HXX_
